# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
use_frameworks!

target 'Pixapals' do
pod 'Alamofire', '~> 3.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'Kingfisher', '~> 1.9'
pod 'IQKeyboardManager'
pod 'MBProgressHUD', '~> 0.9.2'
end

